const countryCodes = [
  { "code": "+356", "name": "Malta" },
    { "code": "+1", "name": "United States" },
    { "code": "+7", "name": "Russia" },
    { "code": "+20", "name": "Egypt" },
    { "code": "+27", "name": "South Africa" },
    { "code": "+30", "name": "Greece" },
    { "code": "+31", "name": "Netherlands" },
    { "code": "+32", "name": "Belgium" },
    { "code": "+33", "name": "France" },
    { "code": "+34", "name": "Spain" },
    { "code": "+36", "name": "Hungary" },
    { "code": "+39", "name": "Italy" },
    { "code": "+40", "name": "Romania" },
    { "code": "+41", "name": "Switzerland" },
    { "code": "+43", "name": "Austria" },
    { "code": "+44", "name": "United Kingdom" },
    { "code": "+45", "name": "Denmark" },
    { "code": "+46", "name": "Sweden" },
    { "code": "+47", "name": "Norway" },
    { "code": "+48", "name": "Poland" },
    { "code": "+49", "name": "Germany" },
    { "code": "+51", "name": "Peru" },
    { "code": "+52", "name": "Mexico" },
    { "code": "+53", "name": "Cuba" },
    { "code": "+54", "name": "Argentina" },
    { "code": "+55", "name": "Brazil" },
    { "code": "+56", "name": "Chile" },
    { "code": "+57", "name": "Colombia" },
    { "code": "+58", "name": "Venezuela" },
    { "code": "+60", "name": "Malaysia" },
    { "code": "+61", "name": "Australia" },
    { "code": "+62", "name": "Indonesia" },
    { "code": "+63", "name": "Philippines" },
    { "code": "+64", "name": "New Zealand" },
    { "code": "+65", "name": "Singapore" },
    { "code": "+66", "name": "Thailand" },
    { "code": "+81", "name": "Japan" },
    { "code": "+82", "name": "South Korea" },
    { "code": "+84", "name": "Vietnam" },
    { "code": "+86", "name": "China" },
    { "code": "+90", "name": "Turkey" },
    { "code": "+91", "name": "India" },
    { "code": "+92", "name": "Pakistan" },
    { "code": "+93", "name": "Afghanistan" },
    { "code": "+94", "name": "Sri Lanka" },
    { "code": "+95", "name": "Myanmar" },
    { "code": "+98", "name": "Iran" },
    { "code": "+211", "name": "South Sudan" },
    { "code": "+212", "name": "Morocco" },
    { "code": "+213", "name": "Algeria" },
    { "code": "+216", "name": "Tunisia" },
    { "code": "+218", "name": "Libya" },
    { "code": "+220", "name": "Gambia" },
    { "code": "+221", "name": "Senegal" },
    { "code": "+222", "name": "Mauritania" },
    { "code": "+223", "name": "Mali" },
    { "code": "+224", "name": "Guinea" },
    { "code": "+225", "name": "Ivory Coast" },
    { "code": "+226", "name": "Burkina Faso" },
    { "code": "+227", "name": "Niger" },
    { "code": "+228", "name": "Togo" },
    { "code": "+229", "name": "Benin" },
    { "code": "+230", "name": "Mauritius" },
    { "code": "+231", "name": "Liberia" },
    { "code": "+232", "name": "Sierra Leone" },
    { "code": "+233", "name": "Ghana" },
    { "code": "+234", "name": "Nigeria" },
    { "code": "+235", "name": "Chad" },
    { "code": "+236", "name": "Central African Republic" },
    { "code": "+237", "name": "Cameroon" },
    { "code": "+238", "name": "Cape Verde" },
    { "code": "+240", "name": "Equatorial Guinea" },
    { "code": "+241", "name": "Gabon" },
    { "code": "+242", "name": "Congo" },
    { "code": "+243", "name": "Democratic Republic of the Congo" },
    { "code": "+244", "name": "Angola" },
    { "code": "+245", "name": "Guinea-Bissau" },
    { "code": "+249", "name": "Sudan" },
    { "code": "+250", "name": "Rwanda" },
    { "code": "+251", "name": "Ethiopia" },
    { "code": "+252", "name": "Somalia" },
    { "code": "+254", "name": "Kenya" },
    { "code": "+255", "name": "Tanzania" },
    { "code": "+256", "name": "Uganda" },
    { "code": "+258", "name": "Mozambique" },
    { "code": "+260", "name": "Zambia" },
    { "code": "+261", "name": "Madagascar" },
    { "code": "+262", "name": "Réunion" },
    { "code": "+263", "name": "Zimbabwe" }
  ];
  
  export default countryCodes;
  